# Generated by Django 4.2 on 2023-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=280, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
