# Generated by Django 4.2 on 2023-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
    ]
