# Generated by Django 4.2 on 2023-07-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
    ]
