# Generated by Django 4.2 on 2023-07-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_tweet_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
    ]
