# Generated by Django 4.2 on 2023-07-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_tweet_creator_alter_tweet_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='tweet_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
